# Generated by Django 6.0.5 on 2026-05-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
